apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express
spec:
  rules:
  - host: 139-144-164-62.ip.linodeusercontent.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: mongo-express-service
            port:
              number: 8081
